spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.125.133
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
---
spring:
  profiles: item-service1  
server:
  port: 8001

---
spring:
  profiles: item-service2  
server:
  port: 8002
